openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        scores:
          type: array
          items:
            type: number
